### ISSUE TITLE
JSON::ParserError: A JSON text must at least contain two octets!

### ISSUE THREAD

**Issue by wulffeld** [sachse/filmbuff#11]
Hi

Was testing out filmbuff to replace the imdb project. 

```
>> fb  = FilmBuff.new
>> fb.search_for_title('Star Wars: Episode VII - The Force Awakens', limit: 2)
JSON::ParserError: A JSON text must at least contain two octets!
        from ../shared/bundle/ruby/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
        from ../shared/bundle/ruby/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `new'
        from ../shared/bundle/ruby/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
        from ../shared/bundle/ruby/2.2.0/gems/filmbuff-1.0.0/lib/filmbuff.rb:88:in `search_for_title'
        from (irb):9
        from ../shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
        from ../shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
        from ../shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
        from ../shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from ../shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
```

Debugging line #88 the response is empty which trips up the JSON.parse.

Searching for just "Star Wars" works fine and returns a result.

**Comment by denkristoffer** [comment]
Thanks for the report. It's easy enough to silence the error, question is if it's possible to actually make it find what you're looking for. I will look into it when I have the time, which probably won't be for a while.

Any help is more than welcome :smiley:
